package com.mycompany.mobpact.model;
// Generated 10 mai 2015 07:59:19 by Hibernate Tools 3.6.0


import com.google.gson.annotations.Expose;
import java.util.Date;

/**
 * Feeds generated by hbm2java
 */

public class Feeds  implements java.io.Serializable {


     private int feedsId;
     private Date timestamp;
     private String url,email,profilepic,status,image,name;
     private transient Participant participant;
     
     

    public Feeds() {
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

	
    public Feeds(int feedsId) {
        this.feedsId = feedsId;
    }
    public Feeds(int feedsId, String name, String image, String status, String profilepic, String url) {
       this.feedsId = feedsId;
       this.name = name;
       this.image = image;
       this.status = status;
       this.profilepic = profilepic;
       this.url = url;
    }

    public int getFeedsId() {
        return feedsId;
    }

    public void setFeedsId(int feedsId) {
        this.feedsId = feedsId;
    }
   
   
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getProfilepic() {
        return this.profilepic;
    }
    
    public void setProfilepic(String profilepic) {
        this.profilepic = profilepic;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public Participant getParticipant() {
        return participant;
    }

    public void setParticipant(Participant participant) {
        this.participant = participant;
    }




}


